---

_This notebook is based on materials from Coursera course [Introduction to data science with python](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG)._

---

# The Python Programming Language: Functions

In [47]:
# create a few statements
x = 1
y = 2
x + y

3

In [48]:
x

1

`add_numbers` is a function that takes two numbers and adds them together.

In [49]:
def add_numbers(x: int, y: int) -> int:
    """
    add two numbers together
    return the result
    """
    return x + y
    
add_numbers(1, 2)

3

In [50]:
add_numbers("a", "b")

'ab'

`add_numbers` updated to take an optional 3rd parameter. Using `print` allows printing of multiple expressions within a single cell.

In [51]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


`add_numbers` updated to take an optional flag parameter.

In [52]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is true!
3


Assign function `add_numbers` to variable `a`.

In [53]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

3

# The Python Programming Language: Types and Sequences

Use `type` to return the object's type.

In [54]:
type('This is a string')

str

In [55]:
type(None)

NoneType

In [56]:
type(1)

int

In [57]:
type(1.0)

float

In [58]:
type(add_numbers)

function

Tuples are an immutable data structure (cannot be altered).

In [59]:
x = (1, 'a', 2, 'b')
type(x)

tuple

Lists are a mutable data structure.

In [60]:
x = [1, 'a', 2, 'b']
type(x)

list

Use `append` to append an object to a list.

In [61]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


This is an example of how to loop through each item in the list.

In [62]:
for item in x:
    print(item)

1
a
2
b
3.3


In [63]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


Or using the indexing operator:

In [64]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


Use `+` to concatenate lists.

In [65]:
[1,2] + [3,4]

[1, 2, 3, 4]

Use `*` to repeat lists.

In [66]:
[1]*3

[1, 1, 1]

Use the `in` operator to check if something is inside a list.

In [67]:
1 in [1, 2, 3]

True

Now let's look at strings. Use bracket notation to slice a string.

In [68]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters


T
T
Th


This will return the last element of the string.

In [69]:
x[-1]

'g'

This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [70]:
x[-4:-2]

'ri'

This is a slice from the beginning of the string and stopping before the 3rd element.

In [71]:
x[:3]

'Thi'

And this is a slice starting from the 3rd element of the string and going all the way to the end.

In [72]:
x[3:]

's is a string'

In [73]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)


Christopher Brooks
ChristopherChristopherChristopher
True


`split` returns a list of all the words in a string, or a list split on a specific character.

In [74]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks


Make sure you convert objects to strings before concatenating.

In [75]:
'Chris' + 2

TypeError: can only concatenate str (not "int") to str

In [80]:
'Chris' + str(2)

'Chris2'

In [81]:
2 + True

3

Dictionaries associate keys with values.

In [78]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator


'brooksch@umich.edu'

In [79]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

Iterate over all of the keys:

In [85]:
for name in x:
    print(name)
    print(x[name])

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


Iterate over all of the values:

In [83]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


Iterate over all of the items in the list:

In [84]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


You can unpack a sequence into different variables:

In [86]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [87]:
fname

'Christopher'

In [88]:
lname

'Brooks'

Make sure the number of values you are unpacking matches the number of variables being assigned.

In [89]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

ValueError: too many values to unpack (expected 3)

# The Python Programming Language: More on Strings

In [90]:
print('Chris' + 2)

TypeError: can only concatenate str (not "int") to str

In [91]:
print('Chris' + str(2))

Chris2


Python has a built in method for convenient string formatting.

In [92]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

# f-strings
print(f'{sales_record["person"]} bought {sales_record["num_items"]} item(s) '
      f'at a price of {sales_record["price"]} each for a total of {sales_record["num_items"]*sales_record["price"]}')


Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96
Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


# Reading and Writing CSV files

Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [95]:
import csv

%precision 2

with open('../data/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 234 dictionaries.

In [96]:
len(mpg)

234

`keys` gives us the column names of our csv.

In [97]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.
We use list comprehesion here.
The notation of list comprehesion is `new_list = [expression for member in iterable]`

In [98]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

Similarly this is how to find the average hwy fuel economy across all cars.

In [99]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

Use `set` to return the unique values for the number of cylinders the cars in our dataset have.

In [102]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.

In [104]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

Use `set` to return the unique values for the class types in our dataset.

In [105]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [106]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

# The Python Programming Language: Dates and Times

In [107]:
import datetime as dt
import time as tm

`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [110]:
tm.time()

1652076587.49

Convert the timestamp to datetime.

In [111]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow.

datetime.datetime(2022, 5, 9, 9, 10, 6, 961762)

Handy datetime attributes:

In [114]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2022, 5, 9, 9, 10, 6)

`timedelta` is a duration expressing the difference between two dates.

In [115]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(days=100)

`date.today` returns the current local date.

In [117]:
today = dt.date.today()

In [119]:
today - delta, today + delta # the date 100 days ago

(datetime.date(2022, 1, 29), datetime.date(2022, 8, 17))

In [120]:
today > today-delta # compare dates

True

# The Python Programming Language: Objects and map()

An example of a class in python:

In [121]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [123]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


Here's an example of mapping the `min` function between two lists.

In [30]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

### The `map()` function.
`map(function, iterable, ...)`

Return an iterator that applies *function* to every item of *iterable*, yielding the result. If additional *iterable* arguments are passed, *function* must take that many arguments and is applied to the items from all iterables in parallel. With multiple iterables, the iterator stops when the shortest iterable is exhausted. For cases where the function inputs are already arranged into argument tuples, see `itertools.starmap()`.

Now let's iterate through the map object to see the values.

In [31]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


# The Python Programming Language: Lambda and List Comprehensions

Here's an example of lambda that takes in three parameters and adds the first two.

In [32]:
my_function = lambda a, b, c : a + b

In [33]:
my_function(1, 2, 3)

3

Let's iterate from 0 to 9 and return the even numbers.

In [34]:
my_list = []
for number in range(0, 9):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0, 2, 4, 6, 8]

Now the same thing but with list comprehension.

In [35]:
my_list = [number for number in range(0,9) if number % 2 == 0]
my_list

[0, 2, 4, 6, 8]

# The Python Programming Language: Numerical Python (NumPy)

In [36]:
import numpy as np

## Creating Arrays

Create a list and convert it to a numpy array

In [37]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

Or just pass in a list directly

In [38]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Pass in a list of lists to create a multidimensional array.

In [39]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

Use the shape method to find the dimensions of the array. (rows, columns)

In [43]:
m.shape

(2, 3)

`arange` returns evenly spaced values within a given interval.

In [44]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

`reshape` returns an array with the same data with a new shape.

In [45]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

`linspace` returns evenly spaced numbers over a specified interval.

In [46]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

`resize` changes the shape and size of array in-place.

In [47]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

`ones` returns a new array of given shape and type, filled with ones.

In [48]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

`zeros` returns a new array of given shape and type, filled with zeros.

In [49]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`diag` extracts a diagonal or constructs a diagonal array.

In [51]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

Create an array using repeating list (or see `np.tile`)

In [52]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Repeat elements of an array using `repeat`.

In [53]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### Combining Arrays

In [54]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

Use `vstack` to stack arrays in sequence vertically (row wise).

In [55]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

Use `hstack` to stack arrays in sequence horizontally (column wise).

In [56]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [57]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [58]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [59]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [60]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [61]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [62]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

The shape of array `z` is `(2,3)` before transposing.

In [63]:
z.shape

(2, 3)

Use `.T` to get the transpose.

In [64]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

The number of rows has swapped with the number of columns.

In [65]:
z.T.shape

(3, 2)

Use `.dtype` to see the data type of the elements in the array.

In [66]:
z.dtype

dtype('int32')

Use `.astype` to cast to a specific type.

In [67]:
z = z.astype('f')
z.dtype

dtype('float32')

## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [68]:
a = np.array([-4, -2, 1, 3, 5])

In [69]:
a.sum()

3

In [70]:
a.max()

5

In [71]:
a.min()

-4

In [72]:
a.mean()

0.6

In [73]:
a.std()

3.2619012860600183

`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [74]:
a.argmax()

4

In [75]:
a.argmin()

0

## Indexing / Slicing

In [76]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [77]:
s[0], s[4], s[-1]

(0, 16, 144)

Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [79]:
s[1:5], s[:]

(array([ 1,  4,  9, 16], dtype=int32),
 array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
       dtype=int32))

Use negatives to count from the back.

In [80]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [81]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

Let's look at a multidimensional array.

In [82]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use bracket notation to slice: `array[row, column]`

In [83]:
r[2, 2]

14

And use : to select a range of rows or columns

In [84]:
r[3, 3:6]

array([21, 22, 23])

Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [85]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

This is a slice of the last row, and only every other element.

In [86]:
r[-1, ::2]

array([30, 32, 34])

We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [87]:
r[r > 30]

array([31, 32, 33, 34, 35])

Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [88]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [89]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

Set this slice's values to zero ([:] selects the entire array)

In [90]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

`r` has also been changed!

In [91]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

To avoid this, use `r.copy` to create a copy that will not affect the original array

In [92]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now when r_copy is modified, r will not be changed.

In [93]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [94]:
test = np.random.randint(0, 10, (4,3))
test

array([[9, 3, 3],
       [2, 8, 7],
       [0, 6, 1],
       [4, 4, 4]])

Iterate by row:

In [95]:
for row in test:
    print(row)

[9 3 3]
[2 8 7]
[0 6 1]
[4 4 4]


Iterate by index:

In [96]:
for i in range(len(test)):
    print(test[i])

[9 3 3]
[2 8 7]
[0 6 1]
[4 4 4]


Iterate by row and index:

In [97]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [9 3 3]
row 1 is [2 8 7]
row 2 is [0 6 1]
row 3 is [4 4 4]


Use `zip` to iterate over multiple iterables.

In [98]:
test2 = test**2
test2

array([[81,  9,  9],
       [ 4, 64, 49],
       [ 0, 36,  1],
       [16, 16, 16]], dtype=int32)

In [99]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[9 3 3] + [81  9  9] = [90 12 12]
[2 8 7] + [ 4 64 49] = [ 6 72 56]
[0 6 1] + [ 0 36  1] = [ 0 42  2]
[4 4 4] + [16 16 16] = [20 20 20]
